# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from tkinter.constants import DISABLED


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

flag = True

def butt_press(event):
    global flag 
    if flag:
        button_2.config(image=button_image_3)
        flag = False
    else:
        button_2.config(image=button_image_2)
        flag = True

window = Tk()

window.geometry("711x426")
window.configure(bg = "#3B6C9B")


canvas = Canvas(
    window,
    bg = "#3B6C9B",
    height = 426,
    width = 711,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("background.png"))
image_1 = canvas.create_image(
    355.0,
    213.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("cat.png"))
image_2 = canvas.create_image(
    558.0,
    279.0,
    image=image_image_2
)

button_image_1 = PhotoImage(
    file=relative_to_assets("talk_button.png"))
button_1 = Button(
    image=button_image_1,
    bg="#3B6C9B",
    activebackground="#3B6C9B",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("talk_button clicked"),
    relief="flat"
)
button_1.place(
    x=177.0,
    y=283.0,
    width=217.0,
    height=56.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("textfield.png"))
entry_bg_1 = canvas.create_image(
    286.0,
    153.5,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0,
    state=DISABLED
)
entry_1.place(
    x=142.0,
    y=67.0,
    width=288.0,
    height=173.0
)

image_image_3 = PhotoImage(
    file=relative_to_assets("microOn.png"))
image_3 = canvas.create_image(
    31.0,
    392.0,
    image=image_image_3
)

button_image_3 = PhotoImage(
    file=relative_to_assets("earphonesOff.png"))

button_image_2 = PhotoImage(
    file=relative_to_assets("earphonesOn.png"))

button_2 = Button(
    image=button_image_2,
    bg="#3B6C9B",
    activebackground="#3B6C9B",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=69.0,
    y=377.0,
    width=30.0,
    height=30.0
)

image_image_4 = PhotoImage(
    file=relative_to_assets("recognition_indicator.png"))
image_4 = canvas.create_image(
    138.0,
    393.0,
    image=image_image_4
)

window.resizable(False, False)
window.title("IWeather")
window.iconphoto(False, PhotoImage(file='cloud.ico'))
button_2.bind('<Button-1>', butt_press)
window.mainloop()