# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
from IWeather import main_func

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from tkinter.constants import DISABLED, NORMAL


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

flag = True

def butt_press(event):
    global flag 
    if flag:
        earphones_indicator.config(image=earphonesOff_image)
        flag = False
    else:
        earphones_indicator.config(image=earphonesOn_image)
        flag = True


def talk_button_pressed(event):
    talk_button.configure(state=DISABLED)
    main_func()
    talk_button.configure(state=NORMAL)
    talk_button.update()

window = Tk()

window.geometry("711x426")
window.configure(bg = "#3B6C9B")


canvas = Canvas(
    window,
    bg = "#3B6C9B",
    height = 426,
    width = 711,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
background_image = PhotoImage(
    file=relative_to_assets("background.png"))
background = canvas.create_image(
    355.0,
    213.0,
    image=background_image

)

cat_image = PhotoImage(
    file=relative_to_assets("cat.png"))
cat = canvas.create_image(
    558.0,
    279.0,
    image=cat_image
)

talk_button_image = PhotoImage(
    file=relative_to_assets("talk_button.png"))
talk_button = Button(
    image=talk_button_image,
    bg="#3B6C9B",
    activebackground="#3B6C9B",
    borderwidth=0,
    highlightthickness=0,
    relief="flat"
)
talk_button.place(
    x=177.0,
    y=283.0,
    width=217.0,
    height=56.0
)


textfield_image = PhotoImage(
    file=relative_to_assets("textfield.png"))
textfield = canvas.create_image(
    286.0,
    153.5,
    image=textfield_image
)
entry_1 = Text(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0,
    state=DISABLED
)
entry_1.place(
    x=142.0,
    y=67.0,
    width=288.0,
    height=173.0
)


microphone_image = PhotoImage(
    file=relative_to_assets("microOn.png"))
microphone_indicator = canvas.create_image(
    31.0,
    392.0,
    image=microphone_image
)

earphonesOff_image = PhotoImage(
    file=relative_to_assets("earphonesOff.png"))

earphonesOn_image = PhotoImage(
    file=relative_to_assets("earphonesOn.png"))

earphones_indicator = Button(
    image=earphonesOn_image,
    bg="#3B6C9B",
    activebackground="#3B6C9B",
    borderwidth=0,
    highlightthickness=0,
    relief="flat"
)
earphones_indicator.place(
    x=69.0,
    y=377.0,
    width=30.0,
    height=30.0
)

recognition_indicator_image = PhotoImage(
    file=relative_to_assets("recognition_indicator.png"))
recognition_indicator = canvas.create_image(
    138.0,
    393.0,
    image=recognition_indicator_image
)

window.resizable(False, False)
window.title("IWeather")
window.iconphoto(False, PhotoImage(file='cloud.ico'))
earphones_indicator.bind('<Button-1>', butt_press)
talk_button.bind('<Button-1>', talk_button_pressed)
window.mainloop()